apiVersion: apps/v1
kind: Deployment
metadata:
  name: servico-pix
  namespace: core-banking
  labels:
    app: servico-pix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servico-pix
  template:
    metadata:
      labels:
        app: servico-pix
    spec:
      containers:
        - name: app
          image: servico-pix:lab
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: LIMITES_URL
              value: http://servico-limites.core-banking.svc.cluster.local:8000
            - name: HTTP_TIMEOUT
              value: "5"
            - name: PIX_USE_OUTBOX
              value: "false"
            - name: PIX_SYNC_KAFKA
              value: "false"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.observability.svc.cluster.local:4317
            - name: OTEL_SERVICE_NAME
              value: servico-pix
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: servico-pix
  namespace: core-banking
spec:
  selector:
    app: servico-pix
  ports:
    - name: http
      port: 8000
      targetPort: 8000
